# fly.toml app configuration file generated for youtube-social-remix-8a1b on 2023-06-04T18:38:08+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "youtube-social-remix-8a1b"
primary_region = "hkg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "bash ./scripts/migrate.sh"

[env]
  METRICS_PORT = "3001"
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"

[metrics]
  port = 3001
  path = "/metrics"
